export const FETCHING_CONTACTS = 'FETCHING_CONTACTS';

export const FETCHING_CONTACTS_SUCCESS = 'FETCHING_CONTACTS_SUCCESS';

export const FETCHING_CONTACTS_FAILURE = 'FETCHING_CONTACTS_FAILURE';


export const FETCHING_TASKS = 'FETCHING_CONTACTS';

export const FETCHING_TASKS_SUCCESS = 'FETCHING_TASKS_SUCCESS';

export const FETCHING_TASKS_FAILURE = 'FETCHING_TASKS_FAILURE';


export const FETCHING_PROJECTS = 'FETCHING_PROJECTS';

export const FETCHING_PROJECTS_SUCCESS = 'FETCHING_PROJECTS_SUCCESS';

export const FETCHING_PROJECTS_FAILURE = 'FETCHING_PROJECTS_FAILURE';


export const FETCHING_MEMBERS = 'FETCHING_MEMBERS';

export const FETCHING_MEMBERS_SUCCESS = 'FETCHING_MEMBERS_SUCCESS';

export const FETCHING_MEMBERS_FAILURE = 'FETCHING_MEMBERS_FAILURE';


// New
export const LOAD_NAVIGATION_ITEMS_START = 'LOAD_NAVIGATION_ITEMS_START';
export const LOAD_NAVIGATION_ITEMS_FAIL = 'LOAD_NAVIGATION_ITEMS_FAIL';
export const LOAD_NAVIGATION_ITEMS = 'LOAD_NAVIGATION_ITEMS';