export const FETCHING_CONTACTS = 'FETCHING_CONTACTS';

export const FETCHING_CONTACTS_SUCCESS = 'FETCHING_CONTACTS_SUCCESS';

export const FETCHING_CONTACTS_FAILURE = 'FETCHING_CONTACTS_FAILURE';


export const FETCHING_TASKS = 'FETCHING_CONTACTS';

export const FETCHING_TASKS_SUCCESS = 'FETCHING_TASKS_SUCCESS';

export const FETCHING_TASKS_FAILURE = 'FETCHING_TASKS_FAILURE';


export const FETCHING_PROJECTS = 'FETCHING_PROJECTS';

export const FETCHING_PROJECTS_SUCCESS = 'FETCHING_PROJECTS_SUCCESS';

export const FETCHING_PROJECTS_FAILURE = 'FETCHING_PROJECTS_FAILURE';


export const FETCHING_MEMBERS = 'FETCHING_MEMBERS';

export const FETCHING_MEMBERS_SUCCESS = 'FETCHING_MEMBERS_SUCCESS';

export const FETCHING_MEMBERS_FAILURE = 'FETCHING_MEMBERS_FAILURE';


// Navigation
export const LOAD_NAVIGATION_ITEMS_START = 'LOAD_NAVIGATION_ITEMS_START';
export const LOAD_NAVIGATION_ITEMS_FAIL = 'LOAD_NAVIGATION_ITEMS_FAIL';
export const LOAD_NAVIGATION_ITEMS = 'LOAD_NAVIGATION_ITEMS';

//Dashboard
export const FETCHING_NEWBOOKINGS = 'FETCHING_NEWBOOKINGS';
export const FETCHING_NEWBOOKINGS_SUCCESS = 'FETCHING_NEWBOOKINGS_SUCCESS';
export const FETCHING_NEWBOOKINGS_FAIL = 'FETCHING_NEWBOOKINGS_FAIL';

export const FETCHING_CURRENTBOOKINGS = 'FETCHING_CURRENTBOOKINGS';
export const FETCHING_CURRENTBOOKINGS_SUCCESS = 'FETCHING_CURRENTBOOKINGS_SUCCESS';
export const FETCHING_CURRENTBOOKINGS_FAIL = 'FETCHING_CURRENTBOOKINGS_FAIL';

export const FETCHING_PAYMENTPENDINGS = 'FETCHING_PAYMENTPENDINGS';
export const FETCHING_PAYMENTPENDINGS_SUCCESS = 'FETCHING_PAYMENTPENDINGS_SUCCESS';
export const FETCHING_PAYMENTPENDINGS_FAIL = 'FETCHING_PAYMENTPENDINGS_FAIL';

export const FETCHING_COMPLETEDBOOKINGS = 'FETCHING_COMPLETEDBOOKINGS';
export const FETCHING_COMPLETEDBOOKINGS_SUCCESS = 'FETCHING_COMPLETEDBOOKINGS_SUCCESS';
export const FETCHING_COMPLETEDBOOKINGS_FAIL = 'FETCHING_COMPLETEDBOOKINGS_FAIL';

export const FETCHING_CANCELLEDBOOKINGS = 'FETCHING_CANCELLEDBOOKINGS';
export const FETCHING_CANCELLEDBOOKINGS_SUCCESS = 'FETCHING_CANCELLEDBOOKINGS_SUCCESS';
export const FETCHING_CANCELLEDBOOKINGS_FAIL = 'FETCHING_CANCELLEDBOOKINGS_FAIL';